### ISSUE TITLE
Getting GOAWAY  error

### ISSUE THREAD

**Issue by mkamioner** [googleapis/nodejs-pubsub#27]
I have been getting the following error a lot after upgrading to `0.15.0`

`Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"`

It seems that the `grpc` module is printing it (it is the only place in my code base where this string exists) and pubsub is the only component using grpc... Anyone else having this problem? What is the impact and how can we stop it?

Thanks!
Mo

#### Environment details

  - OS: Debian 8.10, x86_64 GNU/Linux
  - Node.js version: 6.12.2
  - npm version: 3.10.10
  - @google-cloud/pubsub version: 0.16.1

#### Steps to reproduce

  1. Unsure, we are subscribing with multiple instances to a very active subscription

**Comment by stephenplusplus** [comment]
This issue was moved to grpc/grpc-node#138

**Comment by stephenplusplus** [comment]
Thanks for reporting. I moved the issue to the gRPC repo, since it shouldn't be logging anything unless a user opts-in for that. As far as the error itself (too many pings), is this anything we need to be worried about @callmehiphop?

**Comment by wenbozhu** [comment]
@mkamioner

 Could you describe your deployment environment? The error is likely from a proxy between your client and the GCP service.

**Comment by mkamioner** [comment]
We run on GKE in GCP. We didn't create any proxy between my client and pubsub and I am unaware of any proxies that exist by default.

**Comment by wenbozhu** [comment]
@mkamioner 

Thanks for the info.  One more question, how soon did you see the error, after the stream was opened?

**Comment by marodriguez-llbean** [comment]
I'm getting the same with version 0.16.1

**Comment by mkamioner** [comment]
@wenbozhu in my most recent logs I initiate the connection `08:59:17` and the first error occurs @ `14:03:00`. From that point it consistently re-occurs on the hour but no every hour (strange).

**Comment by baronfel** [comment]
I can also report getting this on version 0.15.0 on node 8.9 on GKE as well.

**Comment by wenbozhu** [comment]
We believe the issue is caused by a bug introduced in grpc 1.7.0  (fixed in 1.8.0).

@y-zeng

The error should only happen when there is no outstanding request on a channel. Let us know if this is not the case.

**Comment by mkamioner** [comment]
We were using 1.8.0  (just double checked) :-/

**Comment by baronfel** [comment]
Same for us, our deployed grpc version is 1.8.0 per the lock file.

**Comment by y-zeng** [comment]
Sorry, the fix was not shipped with 1.8.0. I'm creating a new release (v1.8.4) that includes this fix. I'll update this thread after it's done.

**Comment by nunofgs** [comment]
Yes please! 😄

**Comment by stephenplusplus** [comment]
@y-zeng we've locked our dependency on gRPC to the 1.7.x range, due to a bug introduced in 1.8.0: https://github.com/grpc/grpc-node/issues/130. Do you know if that issue has been resolved?

**Comment by y-zeng** [comment]
I've published the gRPC core v1.8.4 release (https://github.com/grpc/grpc/releases/tag/v1.8.4) which included the PING bug fixes.

@murgatroid99 could you please do a new grpc-node release with v1.8.4?

**Comment by y-zeng** [comment]
@murgatroid99 do you know if there is any update on grpc/grpc-node#130?

**Comment by murgatroid99** [comment]
I expect to be able to publish the grpc-node 1.8.4 by tomorrow, and it has a change that should improve that situation. Specifically, it makes some network errors (I think including that one) report a status of UNAVAILABLE, which should be retried.

**Comment by jkolaric** [comment]
I can see that the grpc-node 1.8.4 is still not published, and there is also no 1.8.4 tag for grpc on npm. When can we expect it to be published?

**Comment by y-zeng** [comment]
grpc-node 1.8.4 has been published. @mkamioner, @baronfel Could you please update grpc-node and verify the fix? Thanks!

**Comment by mkamioner** [comment]
Unfortunately after updating to grpc-node 1.8.4 the bug still occurs :-(

What is the next step @y-zeng ?

**Comment by mkamioner** [comment]
@y-zeng ping...

Bueller? Bueller?... ;-)

**Comment by mkamioner** [comment]
No longer relevant for us. We moved to SQS. I highly recommend getting this SDK stuff together. We were on pubsub for over a year and the we decided that the SDK is just not stable enough right now and we need something that is production ready

**Comment by wenbozhu** [comment]
@mkamioner 

Sorry to hear about this. 

We had been tracking the issue with you and other users on the grpc repo.

https://github.com/grpc/grpc-node/issues/138#issuecomment-354649395

Would still be useful to have the log in case you have it.

Thanks.

**Comment by domparry** [comment]
Just for anyone else that might find this thread.

We have recently had this issue, and I resolved it by having a new `instance` of pubsub for each subscription that we poll in our app. We had around 5 working on a single `instance`, but when we added a sixth we started to get the `Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"` errors.

**Comment by murgatroid99** [comment]
We have what we think is a solution that we will publish in a gRPC patch release soon.

**Comment by murgatroid99** [comment]
We have published gRPC version 1.10.1 with another change that should help with this.

**Comment by webnator** [comment]
Any news on this issue or how to solve it? We're experiencing random peaks of these errors during the day for a couple minutes, and then they seem to resolve. We're seeing this using Spanner.
Any idea what could be causing this, or how to solve it?

**Comment by stephenplusplus** [comment]
@webnator is this still the case using updated dependencies? It might help to confirm what versions you are running.
